import "./globals.css";
import BurgerMenu from "./components/BurgerMenu";


export const metadata = {
  title: "Reggie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link
          href="https://fonts.googleapis.com/css2?family=Edu+AU+VIC+WA+NT+Hand:wght@400..700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body >
        <BurgerMenu />
        {children}
      </body>
    </html>
  );
}


